name: asroo_shop
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  #flutter_facebook_auth: ^6.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
